### PR TITLE
Natneam.about us page

### PR DESCRIPTION
**Pull request by natneam**
======= About us page completed ========
tasks completed => about page created, adding developers section, adding card for each of the developers

### CODE REVIEW

**Review by HananMiftah — APPROVED** [review]
Good Job!!!

**Review by Infinidrix — APPROVED** [review]
Looking good!! The about us cards looked a bit big for me but it's just personal preference 🥇

**Comment by natneam** [comment]
> Looking good!! The about us cards looked a bit big for me but it's just personal preference

It does for me as well but If I make it smaller it would be compacted together which I don't like
Screenshot from 2021-02-08 13-27-03

**Comment by Infinidrix** [comment]
> > Looking good!! The about us cards looked a bit big for me but it's just personal preference
> 
> It does for me as well but If I make it smaller it would be compacted together which I don't like
> Screenshot from 2021-02-08 13-27-03

Yeah that makes sense, we can go with this and see if we can make it better later

**Comment by natneam** [comment]
M

**Pull request merged**
